### PR TITLE
feat: initialize project

### PR DESCRIPTION
**Pull request by aeneasr**

### CODE REVIEW

**Comment by aeneasr** [comment]
Small status update on this front - I implemented all screens! There is also a guide (incomplete...) in the README:

https://github.com/ory/react-nextjs-example/tree/init-example

A few things which are not properly working yet:

- [x] The login screen is not able to properly detect a 2fa flow UNLESS a 2fa flow id is given in it's url. If you have a 2fa flow and call `/login` without flow parameter, you will end up in a weird state where you have to sign out first before you can login again
- [x] All flows are currently using regular submit and not the SDK to submit forms which causes flashing
- [x] No tests

**Comment by Ali-sharafi-git** [comment]
Hi @aeneasr 
Thanks for your sample. 
When I run the project I get a network error
This url is not valid `http://localhost:4000/.ory/sessions/whoami`

Can you please help me on this. thanks


image

**Comment by aeneasr** [comment]
Read the README please. Also it’s a work in progress! Open source is not yet supported!

**Comment by dannycarrera** [comment]
+1 for open source support

**Pull request merged**
